import type { Metadata } from 'next';
import './globals.css';
import 'react-loading-skeleton/dist/skeleton.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="black">
        <main className=" bg-sky-300 min-h-screen w-screen">
          <div className="container mx-auto px-4 py-10">{children}</div>
        </main>
      </body>
    </html>
  );
}
