import type { Metadata } from 'next';
import './globals.css';
import { GlobalStateProvider } from './context/GlobalState';
import { AuthProvider } from './context/Auth';
import Header from './components/Header';
import Providers from './components/Providers';

export const metadata: Metadata = {
  title: 'Art Wise AI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-purple-50">
        <AuthProvider>
          <GlobalStateProvider>
            <Providers>
              <main className="min-h-screen w-screen">
                <Header />
                <div className="container mx-auto px-4 py-10">{children}</div>
              </main>
            </Providers>
          </GlobalStateProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
